=== geekychris/hitorro-all/data/dtds/streamer.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Definition of the adapter source -->
<!ELEMENT  StreamerAdapterSource (Name, ExpressionDefinition, LogicalMappingFile, TableReader, TableData)>
<!ELEMENT  Name (#PCDATA)>
<!ELEMENT  ExpressionDefinition (#PCDATA)>
<!ELEMENT  LogicalMappingFile (#PCDATA)>
<!ELEMENT  TableReader (#PCDATA)>
<!ELEMENT  TableData (#PCDATA)>

<!ELEMENT  LogicalMapping (LogicalColumnDefinition+)>
<!ATTLIST LogicalMapping
name              CDATA    #REQUIRED
>

<!-- logical field definitions -->
<!ELEMENT  LogicalColumnDefinition (Formatter, Field+, Seperator?)>
<!ATTLIST LogicalColumnDefinition
name              CDATA    #REQUIRED
>
<!ELEMENT Field (#PCDATA)>
<!ELEMENT Seperator (#PCDATA)>

<!ELEMENT Formatter (Name, Argument)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Argument (#PCDATA)>
<!ATTLIST Argument
name              CDATA    #REQUIRED
>
<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description
language              CDATA    #REQUIRED
>


<!-- expression defintion -->

<!ELEMENT PSum (Comment?, Description*, PSumOperand+)>
<!ATTLIST PSum
failScore              CDATA    #REQUIRED
>
<!ELEMENT Comment (#PCDATA)>
<!ELEMENT PSumOperand (Comment?, Description*, (NextToOrdered | NextTo| NearOrdered | Near | And | Or | Not))>
<!ATTLIST PSumOperand
score              CDATA    #REQUIRED
>
<!ELEMENT And (Comment?, Description*, (NextToOrdered | NextTo| NearOrdered | Near | And | Or | Not)+)>
<!ELEMENT Or  (Comment?, Description*, (NextToOrdered | NextTo | NearOrdered | Near | And | Or | Not)+)>
<!ELEMENT Not (Comment?, Description*, (NextToOrdered | NextTo| NearOrdered | Near | And | Or | Not))>
<!ELEMENT NextToOrdered (Comment?, Description*, Field)>
<!ELEMENT NextTo (Comment?, Description*, Field)>
<!ELEMENT Near (Comment?, Description*, Field, Score)>
<!ELEMENT NearOrdered (Comment?, Description*, Field, Score)>
<!ELEMENT Score (#PCDATA)>
<!ELEMENT Proximity (#PCDATA)>

=== geekychris/hitorro-all/testinput/streamer/TableExpressionDefinition.xml
<?xml version="1.0"?><!DOCTYPE PSum SYSTEM "streamer.dtd">
<PSum failScore="100">
    <Comment>
        This is a test table meta for
    </Comment>
    <Description language="en">Confidential Employee data</Description>
    <Description language="de">Konfidential mitarbeiter daten</Description>

    <PSumOperand score="100">
        <Comment>
            Fetch the single field that is a credit card number and condition it,
            so that is looks like: nnnn nnnn nnnn nnnn. Optionally will do a mod 11
            check and if its invalid spew out a warning about the content to the log.
        </Comment>
        <And>
            <NextToOrdered>
                <Description language="en">Credit card details</Description>
                <Description language="de">Credit Karte</Description>
                <Field>CreditCardNumber</Field>
            </NextToOrdered>
            <NextToOrdered>
                <Description language="en">Credit card details V 2</Description>
                <Description language="de">Credit Karte V 2</Description>
                <Field>CreditCardNumber</Field>
            </NextToOrdered>
        </And>
    </PSumOperand>
    <PSumOperand score="100">
        <Comment>
            Demonstration of looking for a fist and last name within 10 words of
            each other. Since the first and last name are in seperate fields they
            are fetched and merged with a space as the seperator before
            passing onto the name formatter which simply lower cases the string.
        </Comment>
        <Near>
            <Description language="en">Employee name</Description>
            <Description language="de">Mitarbeiter namen</Description>
            <Field>PersonName</Field>
            <Proximity>10</Proximity>
        </Near>
    </PSumOperand>
</PSum>

=== geekychris/hitorro-all/data/tableloadexample/TableOneLogicalMapping.xml
<?xml version="1.0"?> <!DOCTYPE LogicalMapping SYSTEM "streamer.dtd">
<LogicalMapping name="tableone">
    <LogicalColumnDefinition name="CreditCardNumber">
        <Formatter>
            <Name>CreditCardFormatter</Name>
            <Argument name="warnModElevenCheck">false</Argument>
        </Formatter>
        <Field>CreditCardNumber</Field>
    </LogicalColumnDefinition>

    <LogicalColumnDefinition name="PersonName">
        <Formatter>
            <Name>NameOnlyFormatter</Name>
        </Formatter>
        <Field>FirstName</Field>
        <Field>LastName</Field>
        <Seperator></Seperator>
    </LogicalColumnDefinition>
</LogicalMapping>
